### ISSUE TITLE
Make `depends_on` more robust and extend functionality

### ISSUE THREAD

**Issue by samueljoli** [lalilul3lo/kopye#3]
At the moment, we support conditional questions/prompts by way of the `depends_on` declaration:
```toml
[kind]
type = "Select"
help = "--bin or --lib"
choices = [
  "bin",
  "lib"
]

[is_application]
type = "Confirm"
help = "Is this application code? y/n"
depends_on = "kind::bin"
```
Given the following blueprint, a user would only be prompted for `is_application` only if the user answered `lib` to `kind`. 

As it stands now, the current implementation has it's limitations.
- Limited dependency chaining
  - a question can depend only on a single question.
  - comple dependencies, such as a question depending on multiple conditions (and/or logic) are harder 
   to express

A more robust and long term solution may be to use a DAG and Kahn's algo. A DAG for tracking dependencies and Kahn's algo to determine order.
